Homework 1
================
Yingting Zhang
2023-09-22

# Problem 1

## Load the moderndive library

``` r
library(moderndive)
data("early_january_weather")
```

- the variables in this dataset, including names / values of important
  variables
- the size of the dataset (using nrow and ncol)
- the mean temperature

``` r
early_january_weather
```

    ## # A tibble: 358 × 15
    ##    origin  year month   day  hour  temp  dewp humid wind_dir wind_speed
    ##    <chr>  <int> <int> <int> <int> <dbl> <dbl> <dbl>    <dbl>      <dbl>
    ##  1 EWR     2013     1     1     1  39.0  26.1  59.4      270      10.4 
    ##  2 EWR     2013     1     1     2  39.0  27.0  61.6      250       8.06
    ##  3 EWR     2013     1     1     3  39.0  28.0  64.4      240      11.5 
    ##  4 EWR     2013     1     1     4  39.9  28.0  62.2      250      12.7 
    ##  5 EWR     2013     1     1     5  39.0  28.0  64.4      260      12.7 
    ##  6 EWR     2013     1     1     6  37.9  28.0  67.2      240      11.5 
    ##  7 EWR     2013     1     1     7  39.0  28.0  64.4      240      15.0 
    ##  8 EWR     2013     1     1     8  39.9  28.0  62.2      250      10.4 
    ##  9 EWR     2013     1     1     9  39.9  28.0  62.2      260      15.0 
    ## 10 EWR     2013     1     1    10  41    28.0  59.6      260      13.8 
    ## # ℹ 348 more rows
    ## # ℹ 5 more variables: wind_gust <dbl>, precip <dbl>, pressure <dbl>,
    ## #   visib <dbl>, time_hour <dttm>

``` r
nrow(early_january_weather)
```

    ## [1] 358

``` r
ncol(early_january_weather)
```

    ## [1] 15

``` r
mean(early_january_weather$temp)
```

    ## [1] 39.58212

Short Description: According to the dataset, we can see that there are
15 variables, including origin, year, month, day, hour, temp, dewp,
humid, wind_dir, wind_speed, wind_gust, precip, pressure, visib, and
time_hour. The size of dataset includes 358 rows and 15 columns. The
mean of temperature is 39.5821229.

- make a scatterplot of temp (y) vs time_hour (x):

``` r
library(tidyverse)
```

    ## ── Attaching core tidyverse packages ──────────────────────── tidyverse 2.0.0 ──
    ## ✔ dplyr     1.1.3     ✔ readr     2.1.4
    ## ✔ forcats   1.0.0     ✔ stringr   1.5.0
    ## ✔ ggplot2   3.4.3     ✔ tibble    3.2.1
    ## ✔ lubridate 1.9.2     ✔ tidyr     1.3.0
    ## ✔ purrr     1.0.2     
    ## ── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
    ## ✖ dplyr::filter() masks stats::filter()
    ## ✖ dplyr::lag()    masks stats::lag()
    ## ℹ Use the conflicted package (<http://conflicted.r-lib.org/>) to force all conflicts to become errors

``` r
ggplot(early_january_weather, aes(x = time_hour, y = temp, color = humid)) + geom_point()
```

![](p8105_hw1_yz4434_files/figure-gfm/unnamed-chunk-4-1.png)<!-- -->

## Describe patterns that are apparent in this plot:

As time goes on, the temperature zigzag increased and at the highest
peak, after the date on Jan 14th, it suddenly dropped. As the part of
humidity data, the data between 40-60 make up a large part during the
range of time_hour.

## Export scatterplot to your project directory

``` r
ggsave("scatter_plot.pdf",height = 4, width = 4)
```

# Problem 2

## Create a data frame comprised of:

- a random sample of size 10 from a standard Normal distribution
- a logical vector indicating whether elements of the sample are greater
  than 0
- a character vector of length 10
- a factor vector of length 10, with 3 different factor “levels”

``` r
q2=tibble(
  norm_samp = rnorm(10),
  log_samp = norm_samp > 0,
  character_vec = c ("one","two","three","four","five","six","seven",
                     "eight","nine","ten"),
  factor_vec = factor (c ("LevelA", "LevelB", "LevelC","LevelA", "LevelB", "LevelC",
                        "LevelA", "LevelB", "LevelC","LevelA"))
)
```

## take the mean of each variable in your dataframe. What works and what doesn’t?

``` r
mean (pull (q2,norm_samp))
```

    ## [1] -0.01930541

``` r
mean (pull (q2,log_samp))
```

    ## [1] 0.5

``` r
mean (pull (q2,character_vec))
```

    ## Warning in mean.default(pull(q2, character_vec)): argument is not numeric or
    ## logical: returning NA

    ## [1] NA

``` r
mean (pull (q2,factor_vec))
```

    ## Warning in mean.default(pull(q2, factor_vec)): argument is not numeric or
    ## logical: returning NA

    ## [1] NA

According to the results, we can see that the mean of a random sample of
size 10 is -0.0193054, with the logical vector 0.5, however, the last
two variable which are character vector and factor vector don’t work
because they are neither numeric nor logical returning.

- Using as.numeric function to the logical, character, and factor
  variables

``` r
as.numeric (pull (q2,log_samp ))
as.numeric (pull (q2,character_vec))
as.numeric (pull (q2,factor_vec))
```

According to the results, the result of factor vector shows the values
of 1,2,3 corresponding to the levels of factor; the result of logical
vector convert TRUE as 1 and FALSE as 0; it doesn’t work for character
vector as there is no numeric value in it.

- Explain why or why not when calculate their means?
  - Logical vector: a logical vector can be converted into numeric value
    (TRUE=1, FALSE=0). In this case, this can calculate the mean
  - Character vector: a character vector with character values cannot
    convert into numeric values, which calculate the mean
  - Factor vector: although we can use “as.numeric” function” to convert
    factor levels into numeric format, the data are not truly numeric
    values, presenting levels numerically. In this case, this cannot
    calculate the mean.
